<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="10.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\CNX.Application\CNX.Application.csproj" />
    <ProjectReference Include="..\..\CNX.Shared\CNX.Shared.csproj" />
  </ItemGroup>

</Project>
